### ISSUE TITLE
Remake with GDNative for Godot 3.x

### ISSUE THREAD

**Issue by Olm-e** [StraToN/godotosc#1]
hello,
would this be portable to godot 3.0 ? 
how to help ? (I don't even see how to compile this for now ... hum ... -song of the eternal noob )

**Comment by StraToN** [comment]
I'm really, really sorry: I have to say that this module has never really been functional. It was started a couple of weeks before GDNative was announced, which kind of cancels any interest for Godot modules - thanks to GDNative, you don't need to recompile Godot with your module.

So, this project should be moved to GDNative. Luckily though, this should not be so hard to do. I am waiting for Godot 3.0 stable release.

**Comment by Olm-e** [comment]
ok, so it's clear ;) thanks
will be happy to follow up on this then after 3.0 stable,
there are some cool music/audio-visual project that would use this

**Comment by Olm-e** [comment]
hello, 
any new on this (we talked about a basic port at GodotCon ;) ) ?
I would be happy to test and report :)

**Comment by StraToN** [comment]
Hello :)
Sorry, no time for this project yet :( I need to get GDNative working, which I didn't have the time to do yet.
I have another project due very soon, I'll try to give OSC some love a bit later.

**Comment by StraToN** [comment]
Hi there,
I found a repo that actually made it, but still as a module, not GDNative.
https://github.com/djiamnot/gdosc
Cheers!

**Comment by StraToN** [comment]
@Olm-e I found a GDNative OSC plugin : https://gitlab.com/frankiezafe/gdnative_osc
Cheers ;)
